# Generated by Django 4.0.3 on 2022-04-07 18:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('subtag', models.CharField(blank=True, max_length=30)),
                ('fill_color', models.CharField(default='#AFD9F3', max_length=7)),
                ('text_color', models.CharField(default='#233038', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UT', 'Untreated'), ('IN', 'Inbox'), ('HF', 'Hold File'), ('AR', 'Archive'), ('ER', 'Error')], default='UT', max_length=2)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('document_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('pdf_text', models.TextField(blank=True, editable=False)),
                ('ocr_text', models.TextField(blank=True, editable=False)),
                ('pages', models.IntegerField(editable=False, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='documents', to='sdms.tag')),
            ],
        ),
    ]
