# Generated by Django 4.0.3 on 2022-04-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='counterparty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='file_hash_sha1',
            field=models.CharField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.BinaryField(null=True),
        ),
    ]
